# Generated by Django 3.0.7 on 2020-06-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='post', max_length=150),
            preserve_default=False,
        ),
    ]
